# SPDX-FileCopyrightText: Copyright (c) 2025 Objectionary.com
# SPDX-License-Identifier: MIT

version = 1
[[annotations]]
path = [
    "README.md",
    ".gitignore",
    "**.json"
]
[lint]
exclude = [
  "phino.cabal"
]
precedence = "override"
SPDX-FileCopyrightText = "Copyright (c) 2025 Objectionary.com"
SPDX-License-Identifier = "MIT"
