# SPDX-FileCopyrightText: Copyright (c) 2025 Objectionary.com
# SPDX-License-Identifier: MIT

version = 1
[[annotations]]
path = [
    "README.md"
]
precedence = "override"
SPDX-FileCopyrightText = "Copyright (c) 2025 Objectionary.com"
SPDX-License-Identifier = "MIT"
