# SPDX-FileCopyrightText: Copyright (c) 2025 Objectionary.com
# SPDX-License-Identifier: MIT
# yamllint disable rule:line-length
---
expression: |
  [[ f -> Q.foo(x -> Q.a, y -> $) ]]
result: |-
  \begin{phiquation}
  [[ |f| -> Q . |foo| ( |x| -> Q . |a|, |y| -> \phiTerminal{\xi} ) ]]{.}
  \end{phiquation}
