# SPDX-FileCopyrightText: Copyright (c) 2025 Objectionary.com
# SPDX-License-Identifier: MIT
# yamllint disable rule:line-length
---
xmir: |
  <object>
    <o name="app">
      <o name="x" base=".plus">
        <o base="Φ.number">
          <o>00-00-00-01</o>
        </o>
        <o as="arg" base="Φ.number">
          <o>00-00-00-02</o>
        </o>
      </o>
    </o>
  </object>
phi: '{[[ app -> [[ x -> Q.number([[ D> 00-00-00-01 ]]).plus(arg -> Q.number([[ D> 00-00-00-02 ]])) ]] ]]}'
