# SPDX-FileCopyrightText: Copyright (c) 2025 Objectionary.com
# SPDX-License-Identifier: MIT
# yamllint disable rule:line-length
---
xmir: |
  <object>
    <o name="app">
      <o name="x" base="Φ.org.eolang">
        <o base="Φ.x"/>
        <o as="α1" base=".plus">
          <o base="Φ.y"/>
        </o>
        <o as="arg">
          <o name="y" base="ξ"/>
        </o>
      </o>
    </o>
  </object>
phi: '{[[ app -> [[ x -> Q.org.eolang(α0 -> Q.x)(α1 -> Q.y.plus)(arg -> [[ y -> $ ]]) ]] ]]}'
