# SPDX-FileCopyrightText: Copyright (c) 2025 Objectionary.com
# SPDX-License-Identifier: MIT
---
failure: true
xmir: |
  <object>
    <o name="app">
      <o base="⊥">
        <o base="Φ.number"/>
      </o>
    </o>
  </object>
phi: ''
