# SPDX-FileCopyrightText: Copyright (c) 2025 Objectionary.com
# SPDX-License-Identifier: MIT
# yamllint disable rule:line-length
---
expression: |
  [[ x -> Q.y(z -> "hey", b -> 1) ]]
result: |-
  ⟦
    x ↦ Φ.y(
      z ↦ Φ.string(
        as-bytes ↦ Φ.bytes(
          data ↦ ⟦
            Δ ⤍ 68-65-79,
            ρ ↦ ∅
          ⟧
        )
      )
    )(
      b ↦ Φ.number(
        as-bytes ↦ Φ.bytes(
          data ↦ ⟦
            Δ ⤍ 3F-F0-00-00-00-00-00-00,
            ρ ↦ ∅
          ⟧
        )
      )
    ),
    ρ ↦ ∅
  ⟧
