# SPDX-FileCopyrightText: Copyright (c) 2025 Objectionary.com
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: cabal
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  cabal:
    strategy:
      matrix:
        os: [macos-15, ubuntu-24.04, windows-2022]
        ghc: ['9.6.7', '9.8.4']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - id: setup
        uses: haskell-actions/setup@v2.10.4
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: '3.12.1.0'
      - uses: actions/cache@v5
        with:
          path: |
            ${{ steps.setup.outputs.ghc-path }}
            ${{ steps.setup.outputs.cabal-path }}
            ${{ steps.setup.outputs.cabal-store }}
            dist-newstyle
          key: ${{ runner.os }}-ghc${{ matrix.ghc }}-cabal-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('cabal.project', 'cabal.project.freeze') }}
          restore-keys: |
            ${{ runner.os }}-ghc${{ matrix.ghc }}-cabal-
      - run: cabal update
      - run: make clean test
