# SPDX-FileCopyrightText: Copyright (c) 2025 Objectionary.com
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: ruff
'on':
  pull_request:
    branches:
      - master
    paths:
      - '**.py'
      - 'ruff.toml'
      - '.github/workflows/ruff.yml'
  push:
    branches:
      - master
    paths:
      - '**.py'
      - 'ruff.toml'
      - '.github/workflows/ruff.yml'
permissions: read-all
concurrency:
  group: ruff-${{ github.ref }}
  cancel-in-progress: true
jobs:
  ruff:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - uses: astral-sh/ruff-action@v4.1.0
        with:
          args: check
      - uses: astral-sh/ruff-action@v4.1.0
        with:
          args: format --check
