# SPDX-FileCopyrightText: Copyright (c) 2025 Objectionary.com
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: stack
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
env:
  STACK_ROOT: ${{ github.workspace }}/.stack-root
jobs:
  stack:
    strategy:
      matrix:
        os: [macos-15, ubuntu-24.04, windows-2022]
        ghc: ['9.6.7']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - name: Set up GHC
        id: setup
        uses: haskell-actions/setup@v2.10.3
        with:
          ghc-version: ${{ matrix.ghc }}
          enable-stack: true
          stack-version: '3.5.1'
      - uses: actions/cache@v5
        with:
          path: |
            ${{ env.STACK_ROOT }}
            .stack-work
          key: ${{ runner.os }}-ghc${{ matrix.ghc }}-stack-${{ hashFiles('**/stack.yaml.lock') }}
          restore-keys: |
            ${{ runner.os }}-ghc${{ matrix.ghc }}-stack-
      - run: stack setup
      - run: stack build --fast
      - run: stack test
